version: '3'
services:
  frontend:
    build: ./MEAN-Stack-User-Registration-Front-End/Angular6
    ports:
      - "80:80"
  
  backend:
    build: ./MEAN-Stack-User-Registration---Back-End/Project
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db  # Persistencia de datos

volumes:
  mongo_data:
